### ISSUE TITLE
64 module compiled against a different Node.js 

### ISSUE THREAD

**Issue by Zabrane** [lovell/64#8]
Hi,

I'm having an issue to ship the  `64` module with my NodeJS standalone app on macOS `High Sierra v10.13.6`.

```shell
$ node --version
v15.1.0

$ npm --version
7.0.8

$ npm install
[...]
all good

## package the app as a binary
$ make pkg

## test it
$ ./build/flash
pkg/prelude/bootstrap.js:1244
      throw error;
      ^

Error: The module '/Users/micka/flash/node_src/node_modules/64/build/Release/base64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:805:18)
    at Module.load (internal/modules/cjs/loader.js:651:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:591:12)
    at Function.Module._load (internal/modules/cjs/loader.js:583:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/snapshot/node_src/node_modules/64/index.js:3:16)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

That being said, if i run my app like this, there's no issue at all:
```shell
$ node ./flash.js
```

I even tried to recompile from source (`npm install --build-from-source`), but I got the same error.

Help appreciated.

**Comment by Zabrane** [comment]
Sorry about the noise I wasn't using the right target. All good now.
